import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Tenor_Sans } from "next/font/google";
import "./globals.css";


const fontTitulo = Tenor_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-tenor-sans",
  display: "swap",
});

const fontCuerpo = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${fontTitulo.variable} ${fontCuerpo.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
